### ISSUE TITLE
Terraform Run fails on Terraform Cloud

### ISSUE THREAD

**Issue by yurikoval** [aliksend/terraform-provider-dokku#60]
Error:
```
Error: Unable to establish SSH connection
with provider["registry.terraform.io/aliksend/dokku"]
on main.tf line 21, in provider "dokku":
provider "dokku" {
Unable to establish SSH connection. ssh: handshake failed: open /home/tfc-agent/.tfc-agent/component/terraform/runs/run-yfzfd5ufoxnacRZY/.ssh/known_hosts: no such file or directory
```

![image](https://github.com/aliksend/terraform-provider-dokku/assets/113635/0d70c824-1f05-4bf4-a436-2911d31cd826)

**Comment by aliksend** [comment]
Hi. This [error](https://github.com/aliksend/terraform-provider-dokku/blob/c0fbd4c2409f879e03051e52f389f1bcf8fb4ff5/provider/provider.go#L256) goes from [goph](https://github.com/melbahja/goph/blob/d955155146ed06df49062105dfc6277b1eec7a81/client.go#L74) and from [ssh library](https://pkg.go.dev/golang.org/x/crypto/ssh#Dial). 

Pleas recheck your configuration, did you specify correct ssh_host, ssh_port and ssh_user? Can you do `ssh ssh_user@ssh_host -p ssh_port version` and get something like `dokku version 0.32.0`? If no, then your configuration isn't valid.

**Comment by yurikoval** [comment]
I am able to deploy manually to dokku, and ssh command above works and returns `dokku version 0.30.7`.

**Comment by aliksend** [comment]
I’m working on a solution to this problem.

**Comment by aliksend** [comment]
@yurikoval Can you please check `v1.0.16`? I've added ssh_host_key attribute to set server public key explicitly and not rely on known_hosts file. 

You need to get public key of your server using `ssh-keyscan YOURSERVER`. You can get multiple keys and, I'll be honest, I don't really know what key you should use. You can try every key locally to find the right one.

This key allows to validate that you use the server you expect, not the fake one (for example during man-in-the-middle attack).

**Comment by toanalien** [comment]
Hi @aliksend,

I have created a new pull request to add a feature that allows skipping the known host check. Please review it at your earliest convenience. https://github.com/aliksend/terraform-provider-dokku/pull/66

Thanks!
